### ISSUE TITLE
Issue with nvidia driver download

### ISSUE THREAD

**Issue by rockocoop** [dmc5179/nvidia-driver#1]
I found that the issue i had was due to the fact the the base URL to nvidia when used from my location resulted in a redirect.  The redirect caused the build to fail.

Perhaps add in the readme that the URL used for the driver download should be without redirects.

**Comment by dmc5179** [comment]
I suspect the problem is with this line in the Dockerfile
```
curl -fSsl -O $BASE_URL/$DRIVER_VERSION/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run
```

It is the only curl line without the L option which allows for redirects. I tried launching an EC2 instances in Paris but my curl command still worked without the L so I cannot be sure that it will fix the issue for you. I'm merging in the change anyway since all of the other curl commands have it, and it will definitely fail if there's a redirect.

**Comment by dmc5179** [comment]
https://github.com/dmc5179/nvidia-driver/commit/ad6cb31980adaaaf423428e1472092d413fc2065
